### ISSUE TITLE
Chapter 4: Journal Changes

### ISSUE THREAD

**Issue by Tkael** [EDCD/EDDI#946]
Journal Version 19 – for v3.3 (preview released 20th Sept 2018)
- [X] ~~Simplify the “Category” in MaterialTrade~~  (no action required - we include categories in our material definitions)
- [X] ~~Clarify meaning of bit 14 in status file: was called “under ship” but actually indicates when turret is retracted~~ (no action required)
- [X] ApproachSettlement now includes Latitude and Longitude (@Tkael via #947)
- [X] ~~Note Bounty event is different for Skimmer bounty~~ (no action required - clarification only)
- [X] ~~Update description of StoredShips event with InTransit flag~~ (EDDI does not implement the `StoredShips` event - we prefer the Frontier API data)
- [X] Add ActiveFine info to Docked event (@Tkael via #949)
- [x] EngineerProgress event at startup with summary for all engineers currently known (@Tkael already merged )
- [X] ~~Note a new ShipTargetted event is generated after using KillWarrantScanner, with updated bounty for target~~ (no action required)
- [X] ~~Note the MissionRedirected mission name now has any trailing “_name” removed~~ (no action required)
- [X] Added MyReputation in faction list in FsdJump and Location events (@Tkael via #1002)
- [x] Added “FSDTarget” event when selecting a starsystem to jump to (@Tkael )
- [x] Added MissionID to cargo to indicate if it is mission-related: in Cargo, CollectCargo, EjectCargo events (@Hoodathunk )
- [x] Cargo summary is now written to a separate file, and updated when data changes (@Hoodathunk )
- [x] In ship loadout, indicate if it is ‘hot’
- [x] Add “HullHealth” stat in the “Loadout” event
- [x] MissionCompleted now indicates correct destination after redirection (@Hoodathunk )

Journal Version 20 – for v3.3 (beta 1) (released 30th Oct 2018)
- [X] Multiple faction activestates – in Location and FSDJump events (§4.8,§4.12) (@Tkael via #1002)
- [x] The first “Cargo” event written to the journal contains full inventory (§3.1) (@Hoodathunk )
- [x] Added “AsteroidCracked” event (§7.1)
- [x] Added “SAAScanComplete” (Surface Area Analysis) event (§6.11) (@Tkael via #1002)
- [x] Added “CodexDiscovery” event (§6.1)
- [x] Added “FSSDiscoveryScan” and “FSSSignalScan” events (§6.4,§6.5) (@Tkael via #1002)
- [x] Added several events for Squadrons(§10) (@Hoodathunk  via #1001)
- [x] Add fuel and cargo from Status.json to Status monitor (undocumented change in Journal manual) (@Tkael via #1002)
>`{ "timestamp":"2018-11-05T22:13:11Z", "event":"Status", "Flags":16777224, "Pips":[4,8,0], "FireGroup":3, "GuiFocus":0, "Fuel":15.254974, "Cargo":10.000000 }`

Summary of journal changes for beta2:
- [X] Include info on Faction Happiness– in Location and FSDJump events (§4.8,§4.12) (@Tkael via #1002)
- [x] Fixed bug in MissionAccepted and MissionCompleted for donation missions, where the “Donated” key was written twice, one with a string, once with an int (§8.21,§8.22) (@Hoodathunk )
- [x] Status.json flags indicate if in Analysis mode, and GUI focus shows if in Orrery, FSS, SAA or Codex view (§12) (@Tkael via #1002)
> New GuiFocus values:
>     8    Orrery
>     9    FSS mode
>     10    SAA mode
>     11    Codex
> 
> status flag: bit27    134217728    0x08000000    Hud in Analysis mode

Summary of journal changes for beta3:
- [x] FSSSignalDiscovered – if signal is a USS, add a ThreatLevel value; if signal is a station, add IsStation:true; add SystemAddress (@Tkael via #1002)
- [x] Cargo – fix spurious extra events; add a flag to indicate vessel=Ship or Vessel=SRV (@Hoodathunk )
- [x] CodexEntry: add SystemAddress
- [x] Status.json, Flags: add NightVision flag (bit28/0x10000000) (@Tkael via #1002)
- [x] SendText: include a journal entry for text to squadron or system chat
- [x] ReceiveText: include a ‘Channel’ parameter to show if message was from squadron or system chat (This appears to have broken our filter for system "entering channel" messages) (@Tkael , fixed by #995)
      `{ "timestamp":"2018-11-15T06:16:23Z", "event":"ReceiveText", "From":"", "Message":"$COMMS_entered:#name=ICZ JH-V c2-7;", "Message_Localised":"Entered Channel: ICZ JH-V c2-7", "Channel":"npc" }`
- [x] SAAScanComplete: remove lists of names of discoverers and mappers[*] (@Tkael via #1002)
     * This is because it could include names of XboxOne or PS4 players, and may breach the agreed policies of how we use their personal details

Summary of journal changes for beta4 (known so far):
- [x] ~~Fixed duplicate scan events~~ (Fixed by incorporation of scantype into scan events , but this is good because it means less parsing for us)
- [x] Fix some wing mission cargo reported as stolen (@Hoodathunk )
- [x] FSSSignalDiscovered: add USSType info (@Tkael via #1002 )
- [x] Add new FSSAllBodiesFound event  (@Tkael )
- [x] Scan events generated automatically when entering system will now logged as “ScanType”:”AutoScan” (@Tkael via #1002)
- [x] Add new event MultiSellExplorationData
- [X] Faction info (in FSDJump/Location),  if it's the player's squadron faction, add SquadronFaction:true, and flags HappiestSystem:true or HomeSystem:true if relevant (@Tkael  via #1002)

**Comment by Tkael** [comment]
patch 1
- [ ] Changed new mineable commodity from 'Opal' to 'Void Opals'

**Comment by Tkael** [comment]
- [ ] Unknown ED name PirateAttack in resource EddiDataDefinitions.Properties.FactionStates

**Comment by Tkael** [comment]
- [ ] the Gnosis is now a MegaShipCivilian instead of a MegaShip.

**Comment by Tkael** [comment]
Jan 16 2019 patch notes: Player Journal

 [ ]SquadronStartup event

 [ ]ProspectedAsteroid event

 [ ]ReservoirReplenished event

 [ ] Include station info in Location event, if starting when docked

 [ ]Status.json: more detail on fuel level

 [ ]Status.json: fix GuiFocus value when viewing Codex

 [ ]CodexEntry: fix SystemAddress
